In [54]:
# -*- coding: utf-8 -*-

import csv
import json
import sys
import numpy as np

In [2]:
# Files and inputs
CATEGORIES_FILE = 'categories.json'
DATA_FILE = 'output_data.csv'
ANALYSIS_FILE = 'output_csv.csv'
WORD_BUFFER_SIZE = 400
WORD_OFFSET = 200

In [3]:
# Init
categories = {}
input_data = []
max_values = {}
data = []

In [4]:
# Read categories
with open(CATEGORIES_FILE) as f:
    categories = json.load(f)
    emotions = categories['emotion']

In [5]:
# Init max
for c in categories:
    print(c)
    max_values[c] = 0

emotion
subjectivity
sentiment
orientation
color


In [28]:
# Read data file
input_data = []
with open(DATA_FILE, 'r') as f:
    all_rows = csv.reader(f, delimiter=',')
    headers = next(all_rows, None) # remove header
    rows = []
    for row in all_rows:
        if row != []:
            rows.append(row)
        else:
            continue
    for row in rows:
        entry = {}
        for i, h in enumerate(headers):
            if len(row[i])>1:
                entry[h] = row[i]
            else:
                entry[h] = int(row[i])
        input_data.append(entry)

In [44]:
# list of lists of dictionaries(word + emotions + review number) of each review 
list_of_reviews = []

amount_reviews = set()
for row in input_data:
    i = int(row['review'])
    amount_reviews.add(i)

for i in range(len(amount_reviews)):
    review = []
    for row in input_data:
        if int(row['review']) == i:
            review.append(row)
    list_of_reviews.append(review)

In [53]:
print(list_of_reviews[0][0])

{'english word': 'stay', 'anger': 0, 'fear': 0, 'anticipation': 0, 'trust': 0, 'surprise': 0, 'sadness': 0, 'joy': 0, 'disgust': 0, 'review': 0}


In [85]:
anger_score = []
fear_score = []
anticipation_score = []
trust_score = []
surprise_score = []
sadness_score = []
joy_score = []
disgust_score = []

In [86]:
scores=[]
for review in list_of_reviews:
    amount_of_words = len(review)
    anger = []
    fear = []
    anticipation = []
    trust = []
    surprise = []
    sadness = []
    joy = []
    disgust = []
    for i in range(amount_of_words):
        anger.append(review[i]['anger'])
        fear.append(review[i]['fear'])
        anticipation.append(review[i]['anticipation'])
        trust.append(review[i]['trust'])
        surprise.append(review[i]['surprise'])
        sadness.append(review[i]['sadness'])
        joy.append(review[i]['joy'])
        disgust.append(review[i]['disgust'])
    anger_score.append(sum(anger)/amount_of_words)
    fear_score.append(sum(fear)/amount_of_words)
    anticipation_score.append(sum(anticipation)/amount_of_words)
    trust_score.append(sum(trust)/amount_of_words)
    surprise_score.append(sum(surprise)/amount_of_words)
    sadness_score.append(sum(sadness)/amount_of_words)
    joy_score.append(sum(joy)/amount_of_words)
    disgust_score.append(sum(disgust)/amount_of_words)

scores.append(anger_score)
scores.append(fear_score)
scores.append(anticipation_score)
scores.append(trust_score)
scores.append(surprise_score)
scores.append(sadness_score)
scores.append(joy_score)
scores.append(disgust_score)

In [88]:
print(scores[0])

[0.0, 0.034482758620689655, 0.038461538461538464, 0.0]


In [89]:
scores=np.array(scores)

In [94]:
print(scores)

[[ 0.          0.03448276  0.03846154  0.        ]
 [ 0.          0.03448276  0.          0.        ]
 [ 0.04615385  0.03448276  0.          0.04705882]
 [ 0.07692308  0.06896552  0.          0.08235294]
 [ 0.          0.06896552  0.          0.01176471]
 [ 0.          0.06896552  0.03846154  0.01176471]
 [ 0.06153846  0.10344828  0.          0.03529412]
 [ 0.          0.03448276  0.07692308  0.        ]]


In [102]:
# Read categories
with open(CATEGORIES_FILE) as f:
    categories = json.load(f)
    emotions = categories['emotion']

In [111]:
m,n = np.shape(scores)
list_scores=[]

for i in range(n):
    rew_scores={}
    #print('i: ', i)
    for j, emotion in enumerate(emotions):
     #   print('j: ', j)
      #  print('emotion: ', emotion)
        rew_scores[emotion] = scores[j,i]
    list_scores.append(rew_scores)

In [114]:
list_scores

[{'anger': 0.0,
  'anticipation': 0.046153846153846156,
  'disgust': 0.0,
  'fear': 0.0,
  'joy': 0.061538461538461542,
  'sadness': 0.0,
  'surprise': 0.0,
  'trust': 0.076923076923076927},
 {'anger': 0.034482758620689655,
  'anticipation': 0.034482758620689655,
  'disgust': 0.034482758620689655,
  'fear': 0.034482758620689655,
  'joy': 0.10344827586206896,
  'sadness': 0.068965517241379309,
  'surprise': 0.068965517241379309,
  'trust': 0.068965517241379309},
 {'anger': 0.038461538461538464,
  'anticipation': 0.0,
  'disgust': 0.076923076923076927,
  'fear': 0.0,
  'joy': 0.0,
  'sadness': 0.038461538461538464,
  'surprise': 0.0,
  'trust': 0.0},
 {'anger': 0.0,
  'anticipation': 0.047058823529411764,
  'disgust': 0.0,
  'fear': 0.0,
  'joy': 0.035294117647058823,
  'sadness': 0.011764705882352941,
  'surprise': 0.011764705882352941,
  'trust': 0.082352941176470587}]